TEMPLATE = subdirs
SUBDIRS +=
SUBDIRS +=
SUBDIRS +=
SUBDIRS +=
SUBDIRS +=
SUBDIRS += monitorfixture
SUBDIRS += monitorfixtureitem
SUBDIRS += palettegenerator
SUBDIRS += vcbutton
SUBDIRS += vccuelist
SUBDIRS += vcframe
SUBDIRS +=
SUBDIRS += vclabel
SUBDIRS += vcproperties
SUBDIRS += vcwidget
SUBDIRS += vcwidgetproperties
SUBDIRS += vcxypad
SUBDIRS += vcxypadarea
SUBDIRS += vcxypadfixture
SUBDIRS +=
